# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-26 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CveItemInfoAdd',
            fields=[
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('itemUrl', models.CharField(default='', max_length=500, verbose_name='cveId')),
                ('dataSource', models.CharField(default='', max_length=256, verbose_name='数据源')),
                ('desc', models.TextField(default='', null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '待跟踪cve',
                'db_table': 'cveiteminfoadd',
            },
        ),
        migrations.DeleteModel(
            name='CveItem',
        ),
    ]
