# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0002_auto_20201026_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveiteminfoadd',
            name='collections_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='搜集数据时间'),
            preserve_default=False,
        ),
    ]
