# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTask', '0004_auto_20201026_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logDetail',
            field=models.TextField(null=True, verbose_name='日志详情'),
        ),
    ]
